title: "[RFC]: "
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area topic is related to?
      options:
        - git
        - web
        - mobile
        - api
        - security
        - infra
    validations:
      required: true

  - type: markdown
    id: area
    attributes:
      label: What do you want to discuss
    validations:
      required: true

  - type: textarea
    id: ehy
    attributes:
      label: Why this is important
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
